version: '3.8'

services:
  react-app:
    image: node:20-alpine
    container_name: react-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    stdin_open: true
    tty: true
